server:
  port: 8888
  servlet:
    context-path: /api
    application-display-name: case manager

spring:
  application:
    name: case manager
  security:
    user:
      name: user
      password: 111111
  # 配置数据源
  datasource:
    # MySQL在高版本需要指明是否进行SSL连接 解决则加上 &useSSL=false
    # JDBC 连接到mysql-connector-java 6+以上的需要指定时区 serverTimezone=GMT%2B8
    url: jdbc:mysql://cdb-4x9gogum.bj.tencentcdb.com:10247/case_manager?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: sJ8UPhQ_LA94tUm
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      stat-view-servlet:
        # 默认true 内置监控页面首页/druid/index.html
        enabled: true
        url-pattern: /druid/*
        # 允许清空统计数据
        reset-enable: true
        login-username: root
        login-password: 111111
        # IP白名单 多个逗号分隔
        allow:
      filter:
        stat:
          enabled: true
        wall:
          enabled: true
          config:
            selelct-allow: true
            select-into-allow: true
            delete-allow: true
            insert-allow: true
            replace-allow: true
            set-allow: true
            multi-statement-allow: true
        slf4j:
          enabled: true
          statement-create-after-log-enabled: false
          statement-close-after-log-enabled: false
          result-set-open-after-log-enabled: false
          result-set-close-after-log-enabled: false
      initial-size: 5
      max-active: 30


# mybatis-plus相关配置
mybatis-plus:
  # xml扫描，多个目录用逗号或者分号分隔（告诉 Mapper 所对应的 XML 文件位置）
  mapper-locations: classpath*:mapper/*/*Mapper.xml

#  global-config:
#    db-config:
#      id-type: auto
#      table-underline: true
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  # 实体扫描
  type-aliases-package: com.mone.server.casemanagerstart.*.entity

swagger:
  title: CaseManager API Documentation
  description: 用例管理系统API文档
  version: 1.0.0
  contact:
    name: MoTao
    url: http://blog.exrick.cn
    email: motao@360.cn

jwt:
  header: Authorization
  tokenHead: "Bearer "
  issuer: lancemone
  expiration: 604800
  secret: C*F-JaNdRgUkXn2r5u8x/A?D(G+KbPeShVmYq3s6v9y$B&E)H@McQfTjWnZr4u7w
  verify: verify
  ignoreUrls:
    - /
    - /login
    - /swagger-ui.html
    - /swagger-resources/configuration/ui
    - /v2/api-docs
    - /**/*.html
    - /**/*.css
    - /**/*.js
    - /**/*.png

