case-manager:
  # 是否启用ansi控制台输出有颜色的字体，dev环境建议开启，服务器环境设置为false
  enable-ansi: true
  # 当前环境服务IP地址
  server-ip: 127.0.0.1
  # 文件上传下载配置
  upload-path: /opt/upload/


# 服务器: 211.149.213.243:22000   root tecu5puc   worker 1234qwer

spring:
  datasource:
    # MySQL在高版本需要指明是否进行SSL连接 解决则加上 &useSSL=false
    # JDBC 连接到mysql-connector-java 6+以上的需要指定时区 serverTimezone=GMT%2B8
    url: jdbc:mysql://cdb-lo0x1fd2.bj.tencentcdb.com:10164/case_manager?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: 7eYvAb!9X6ziFNX

  # Redis配置
  redis:
    database: 0
    host: 211.149.213.243
    password: tecu5puc
    port: 6379
    jedis:
      pool:
        max-active: 10
        max-wait: -1
    timeout: 10000

# 打印SQL语句和结果集，本地开发环境可开启，线上注释掉
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
