case-manager:
  # 是否启用ansi控制台输出有颜色的字体，local环境建议开启，服务器环境设置为false
  enable-ansi: false
  # 当前环境服务IP地址
  server-ip:
  # 生产环境禁用Swagger
  swagger:
    enable: false
  # AOP配置
  aop:
    log:
      enable: true
      log-print-type: NONE
      request-log-format: false
      response-log-format: false

spring:
  datasource:
    url: jdbc:mysql://cdb-4x9gogum.bj.tencentcdb.com:10247/case_manager?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF8&zeroDateTimeBehavior=convertToNull&useSSL=false&serverTimezone=GMT%2B8
    username: root
    password: sJ8UPhQ_LA94tUm

  # Redis配置
  redis:
    database: 0
    host: 127.0.0.1
    password: tecu5puc
    port: 6379

